### ISSUE TITLE
Add REST API logging

### ISSUE THREAD

**Issue by microbuilder** [microbuilder/linaroca#14]
Access requests to the REST API should be logged to detect malicious connections, such as too many requests in too short a duration of time, and just to trace use of the various endpoints.

**Comment by d3zd3z** [comment]
I would suggest we follow the guidelines of: https://12factor.net/, and just log message to stdout. On a modern cloud environment, our service will be run in a container, and external systems will managing logging all of the services. Even systemd now expects logging to just be done to stdout.
