### ISSUE TITLE
Use a device-class key for registration

### ISSUE THREAD

**Issue by d3zd3z** [microbuilder/linaroca#20]
Right now, anyone can connect to the CA port, give a CRT, and be issued to certificate (and even be registered as a device). As a beginning level of security, we can create a device-class key which is used by all of the devices in one class to register. This would need to present a client certificate during the handshake to prove the device is valid. Probably initially, we could compile this private key into the image directly.

**Comment by microbuilder** [comment]
As discussed, lets rename this to 'Bootstrap Key/Cert'

**Comment by d3zd3z** [comment]
Resolved by #26
