### ISSUE TITLE
Enable certificate invalidation via blocklist

### ISSUE THREAD

**Issue by microbuilder** [microbuilder/linaroca#3]
A blocklist table should be added to the DB to block issued certificates.

- Certificates can be blocked via `api/v1/krr`
- Their current status can be checked via `api/v1/cs/{serial}`
- A timestamp, requestor ID, and optional `reason` field should be associated with the blocklist record

**Comment by d3zd3z** [comment]
It turns out this is pretty easy to fix, see #5.

**Comment by microbuilder** [comment]
Initial DB changes added via #10
