### ISSUE TITLE
Add additional DNs for CSR

### ISSUE THREAD

**Issue by microbuilder** [microbuilder/linaroca#9]
The following DNs should be added to the sample CSR to ensure best practices are followed:

- [x] CN (Common Name)
- [x] O (Organisation Name)
- [ ] OU (Organisation Unit)
- [ ] C (Country)
- [ ] S (State)
- [ ] L (Locality)
- [ ] EMAIL (Organisation contact) 

* `EMAIL` is optional, but may be useful in the certificate?

**Comment by d3zd3z** [comment]
Actually, according to RFC7925, and convention, for device identifying things, generally only CN is used, and it should be set to the 64-bit EUID of the device. Not everyone uses EUID (many use a UUID). The rest of the fields are pretty meaningless for a device certificate. The CN should be first.
